baseURL = 'https://devxlog.github.io'
languageCode = 'en-us'
title = 'devXlog tech blog'
theme = 'hugo-theme-stack'

[params]
  favicon = "images/favicon.ico"
  [params.sidebar]
     subtitle = '@WEMADE'
     